---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database
automountServiceAccountToken: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-port: "5432"
      labels:
        app: database
    spec:
      serviceAccountName: database
      containers:
        - name: database
          image: shipyardrun/postgres:9.6
          imagePullPolicy: Always
          env:
            - name: POSTGRES_DB
              value: root
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: please_change_me_barry
          volumeMounts:
            - name: pgdata
              mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: pgdata
          emptyDir: {}