---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
automountServiceAccountToken: true

---
# Payments service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "payments"
        vault.hashicorp.com/agent-inject-secret-config: "database/creds/db-payments"
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "database/creds/db-payments" -}}
          export DATABASE_USER="{{ .Data.username }}"
          export DATABASE_PASSWORD="{{ .Data.password }}"
          export DATABASE_NAME="root"
          {{- end }}
          npm start
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-port: "3000"
        consul.hashicorp.com/connect-service-upstreams: "database:5432"
      labels:
        app: payments
    spec:
      serviceAccountName: payments
      containers:
      - name: payments
        image: nicholasjackson/emojify-favorites:v0.2.0
        command: ['sh', '/vault/secrets/config']
        env:
        - name: "BIND_ADDR"
          value: "127.0.0.1"