---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
automountServiceAccountToken: true

---
# Payments service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-port": "9090"
        "consul.hashicorp.com/connect-service-upstreams": "database:5432"
      labels:
        app: payments
    spec:
      serviceAccountName: payments
      containers:
      - name: payments
        image: nicholasjackson/fake-service:v0.9.0
        env:
        - name: "LISTEN_ADDR"
          value: "127.0.0.1:9090"
        - name: "NAME"
          value: "payments"
        - name: "MESSAGE"
          value: "Payment"
        - name: "HTTP_CLIENT_KEEP_ALIVES"
          value: "true"
