---
# Secret that gives the application access to the database.
apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
data:
  username: cm9vdA==
  password: cGxlYXNlX2NoYW5nZV9tZV9iYXJyeQ==
  database: cm9vdA==

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: search
automountServiceAccountToken: true

---
# Service to expose the search service
apiVersion: v1
kind: Service
metadata:
  name: search
spec:
  selector:
    app: search
  ports:
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 3000

---
# Search service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  labels:
    app: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-port: "3000"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "search"
        vault.hashicorp.com/agent-inject-secret-config: "database/creds/db-search"
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "database/creds/db-search" -}}
          export POSTGRES_USER="{{ .Data.username }}"
          export POSTGRES_PASS="{{ .Data.password }}"
          export POSTGRES_DB="root"
          {{- end }}
          env
          npm start
      labels:
        app: search
    spec:
      serviceAccountName: search
      containers:
      - name: search
        image: nicholasjackson/emojify-favorites:v0.1.0
        command: ['sh', '/vault/secrets/config']
        ports:
        - containerPort: 3000
