---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
automountServiceAccountToken: true

---
# Service to expose the search service
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  selector:
    app: payments
  ports:
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 3000

---
# Payments service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "payments"
        vault.hashicorp.com/agent-inject-secret-config: "database/creds/db-payments"
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "database/creds/db-payments" -}}
          export DATABASE_USER="{{ .Data.username }}"
          export DATABASE_PASSWORD="{{ .Data.password }}"
          export DATABASE_NAME="root"
          {{- end }}
          npm start
      labels:
        app: payments
    spec:
      serviceAccountName: payments
      containers:
      - name: payments
        image: nicholasjackson/emojify-favorites:v0.1.0
        command: ['sh', '/vault/secrets/config']
        ports:
        - containerPort: 3000