---
# Secret that gives the application access to the database.
apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
data:
  username: cm9vdA==
  password: cGxlYXNlX2NoYW5nZV9tZV9iYXJyeQ==
  database: cm9vdA==

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: search
automountServiceAccountToken: false

---
# Service to expose the search service
apiVersion: v1
kind: Service
metadata:
  name: search
spec:
  selector:
    app: search
  ports:
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 3000

---
# Search service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  labels:
    app: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      serviceAccountName: search
      containers:
      - name: search
        image: nicholasjackson/emojify-favorites:v0.1.0
        ports:
        - containerPort: 3000
        env:
        - name: "DATABASE_USER"
          valueFrom:
            secretKeyRef:
              name: database
              key: username
        - name: "DATABASE_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: database
              key: password
        - name: "DATABASE_NAME"
          valueFrom:
            secretKeyRef:
              name: database
              key: database
