# Available parameters and their default values for the Consul chart.
# Server, when enabled, configures a server cluster to run. This should
# be disabled if you plan on connecting to a Consul cluster external to
# the Kube cluster.
global:
  name: consul
  image: "consul:1.9.0-beta2"
  acls:
    manageSystemACLs: true
server:
  replicas: 1
  bootstrapExpect: 1
controller:
  enabled: true
ui:
  enabled: true
connectInject:
  enabled: true
  default: false
  centralConfig:
    enabled: "true"
    defaultProtocol: "tcp"
