---
# Service to expose the database
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
  - name: http
    protocol: TCP
    port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: postgres
          image: shipyardrun/postgres:9.6
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: root
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: please_change_me_barry
          volumeMounts:
            - name: pgdata
              mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: pgdata
          emptyDir: {}